# 사용자님의 파일 구조를 그대로 유지합니다. (최상위 'waypoints:' 없음)
# --- 1번 라인 ---
A1:
  position: {x: -5.54, y: 5.76}
  neighbors: [B1, A2]
B1:
  position: {x: -5.76, y: 4.9}
  neighbors: [A1, C1]
C1:
  position: {x: -5.79, y: 3.25}
  neighbors: [B1]

# --- 2번 라인 ---
A2:
  position: {x: -3.59, y: 5.69}
  neighbors: [A1, A3]

# --- 3번 라인 ---
A3:
  position: {x: -0.19, y: 5.53}
  neighbors: [A2, B3]
B3:
  position: {x: 0.01, y: 4.01}
  neighbors: [A3, C3]
C3:
  position: {x: 0.06, y: 2.7}
  neighbors: [B3, D3, C4]
D3:
  position: {x: 0.03, y: 0.96}
  neighbors: [C3, E3]
E3:
  position: {x: 0.05, y: -0.34}
  neighbors: [D3, E4]

# --- 4번 라인 ---
C4:
  position: {x: 1.61, y: 2.65}
  neighbors: [C3, C5]
E4:
  position: {x: 1.66, y: -0.53}
  neighbors: [E3, E5]

# --- 5번 라인 ---
C5:
  position: {x: 2.97, y: 2.57}
  neighbors: [C4, D5, C6]
D5:
  position: {x: 2.92, y: 0.98}
  neighbors: [C5, E5]
E5:
  position: {x: 3.06, y: -0.51}
  neighbors: [E4, D5, E6]

# --- 6번 라인 ---
C6:
  position: {x: 4.45, y: 2.58}
  neighbors: [C5, C7]
E6:
  position: {x: 4.53, y: -0.53}
  neighbors: [E5, E7]

# --- 7번 라인 ---
C7:
  position: {x: 5.74, y: 2.49}
  neighbors: [C6, C8, D7]
D7:
  position: {x: 5.74, y: 1.18}
  neighbors: [C7, E7]
E7:
  position: {x: 5.74, y: -0.12}
  neighbors: [D7, E6, E8]

# --- 8번 라인 ---
C8:
  position: {x: 7.53, y: 2.36}
  neighbors: [C7, C9]
E8:
  position: {x: 7.67, y: -0.10} # y좌표 오타 수정
  neighbors: [E7, E9]

# --- 9번 라인 ---
C9:
  position: {x: 8.97, y: 1.96}
  neighbors: [C8, D9] # 이웃 논리 오류 수정
D9:
  position: {x: 9.10, y: 1.11}
  neighbors: [C9, E9]
E9:
  position: {x: 8.98, y: -0.16}
  neighbors: [E8, D9]